### ISSUE TITLE
Future warnings issue + improvement required in get_price_chart

### ISSUE THREAD

**Issue by mattiacostacurta** [mattiacostacurta/bitstamp#17]
FutureWarning: Columnar iteration over characters will be deprecated in future releases.
price_df["Date"], price_df["Time"] = price_df["Date and time"].str.split(" ", 1).str

The graph should display values in a descending way, from the previous hour to the current moment.

**Comment by ginevrabarbieri** [comment]
99b8031 
df8e09a
