### ISSUE TITLE
Necessary to divide the get_price_chart function in sub functions and solve the bug of time

### ISSUE THREAD

**Issue by ginevrabarbieri** [mattiacostacurta/bitstamp#22]
Bug referred to "list of index out of range" referred to:
for n in range (0, len(df)+1, int(len(df)/6)):
        time_values.append(timing[n])

**Comment by calzavarateres** [comment]
f7d815c4cbf4de9f22c87f996ec63a8b8fdc294e

**Comment by calzavarateres** [comment]
2f6634a5505f1be7a07f02554cd322dad8e673b1
